openapi: 3.0.0
/process_image:
  post:
    summary: Process an image
    parameters:
      - in: inputData
        name: filename
        type: file
        required: true
        description: The image file to process
      - in: data
        name: Operations
        type: dictionary
        items:
          type: string
        required: true
        description: The operations to perform on the image
    responses:
      200:
        description: OK
        schema:
          type: string
          format: binary
      400:
        description: Bad Request
        schema:
          $ref: '#/definitions/Error'
      500:
        description: Internal Server Error
        schema:
          $ref: '#/definitions/Error'

---
definitions:
  Error:
    type: object
    properties:
      error:
        type: string
        description: The error message
